### ISSUE TITLE
Fix the extension to work when the akinga.org URL changes

### ISSUE THREAD

**Issue by eunikolsky** [phoenixrvd/Books-Downloader#3]
As mentioned in #2, akniga.org now uses Single Page Application paradigm, it doesn't reload the entire page when you go to different books, so the callback in `loader.js` is called only when the extension is reloaded or the webpage is manually refreshed. This results in weird behavior: if you open a tab with one book, then a new tab with another book, and switch to the first one, the toolbar button's hint will say the second book's title.

The extension should track URL changes in a tab and offer to download the current book.

Some ideas:
* prepare book data and download the book when the user clicks on the toolbar button — then the extension will use the current page;
  * but the question is how to track the current tab and disable the button on non-matching tabs;
* a better approach may be to use an [address bar button](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Page_actions) instead; it will be displayed only on the matching domain by the browser (less code in the extension) and it fits the domain-specific extension workflow more.

**Comment by phoenixrvd** [comment]
Thank you for the analysis. I will validate your suggestions in the near future and give my feedback regarding this.
