### ISSUE TITLE
Не работает.

### ISSUE THREAD

**Issue by fabrikant** [phoenixrvd/Books-Downloader#6]
Файлы не скачиваются

**Comment by phoenixrvd** [comment]
Спасибо за уведомление. Недавно мы выпустили новую версию (2.0.13). Она доступна в магазине Firefox и здесь, на GitHub.

**Comment by phoenixrvd** [comment]
Спасибо за сообщение. Недавно мы выпустили новую версию (2.0.13). Она доступна в магазине Firefox и здесь, на GitHub. Теперь должно работать.
